# Generated by Django 2.1.7 on 2019-03-08 04:50

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=300, null=True),
        ),
    ]
